apiVersion: tcp.ei.telekom.de/v1
kind: Rover
metadata:
  name: provider-app
spec:
  zone: aws
  exposures:
  - basePath: "/geographicAddressManagement/v1"
    upstream: "http://geographic-address-api.preprod.tif.telekom.de/"
    approval: "AUTO"

